Models/ErrorViewModel.cs
namespace UseCase14.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/TestController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UseCase14.Models;

namespace UseCase14.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["Layout_Header"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UseCase14.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Test" asp-action="Index">@Localizer["Layout_Header"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">@Localizer["Layout_TestPage"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Privacy">@Localizer["Layout_PrivacyPage"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - @Localizer["Layout_Header"] - <a asp-area="" asp-controller="Test" asp-action="Privacy">@Localizer["Layout_PrivacyPage"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Test/Index.cshtml
@using UseCase14.Controllers
@using Microsoft.Extensions.Localization;
@using System.Globalization;
@using UnitsNet;
@inject IStringLocalizer<TestController> Localizer

@{
    ViewData["Title"] = Localizer["Index_Title"];

    DateTime datetime = DateTime.Now;

    int var1 = -1024652;
    int var2 = 1024652588;
    double var3 = -6755334.565446;
    double var4 = 5334.565446;

    Length someLength = Length.FromMeters(1234.567);
    Volume someVolume = Volume.FromLiters(1234.567);
    Mass someMass = Mass.FromKilograms(1234.567);
}

<div class="text-center">
    <h1 class="display-4">@Localizer["Index_Header"]</h1>
    <p>@Localizer["Index_MainText"]</p>
    <br />

    <p>@datetime.ToString(CultureInfo.CurrentCulture)</p>
    <p>@datetime.ToLongDateString()</p>
    <p>@datetime.ToLongTimeString()</p>
    <p>@datetime.ToShortTimeString()</p>
</div>

<table class="table" role="presentation">
    <tbody>
        <tr>
            <td>@var1.ToString("n", CultureInfo.CurrentCulture)</td>
            <td>@var1.ToString("e4", CultureInfo.CurrentCulture)</td>
            <td>@var1.ToString("C", CultureInfo.CurrentCulture)</td>
        </tr>
        <tr>
            <td>@var2.ToString("n", CultureInfo.CurrentCulture)</td>
            <td>@var2.ToString("e4", CultureInfo.CurrentCulture)</td>
            <td>@var2.ToString("C", CultureInfo.CurrentCulture)</td>
        </tr>
        <tr>
            <td>@var3.ToString("n", CultureInfo.CurrentCulture)</td>
            <td>@var3.ToString("e4", CultureInfo.CurrentCulture)</td>
            <td>@var3.ToString("C", CultureInfo.CurrentCulture)</td>
        </tr>
        <tr>
            <td>@var4.ToString("n", CultureInfo.CurrentCulture)</td>
            <td>@var4.ToString("e4", CultureInfo.CurrentCulture)</td>
            <td>@var4.ToString("C", CultureInfo.CurrentCulture)</td>
        </tr>
    </tbody>
</table>

<div class="text-center">
    <p>@someLength.ToLocalizedString(CultureInfo.CurrentCulture)</p>
    <p>@someVolume.ToLocalizedString(CultureInfo.CurrentCulture)</p>
    <p>@someMass.ToLocalizedString(CultureInfo.CurrentCulture)</p>
</div>